# Generated by Django 4.1.2 on 2022-10-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lct4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
