# Generated by Django 4.1.2 on 2022-11-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lct4', '0002_customusers_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=16)),
                ('date', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=64)),
                ('product', models.IntegerField()),
                ('somenum1', models.IntegerField()),
                ('somenum2', models.IntegerField()),
                ('somenum3', models.IntegerField()),
                ('region', models.CharField(max_length=256)),
                ('district', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
