# Generated by Django 4.1.2 on 2022-11-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lct4', '0003_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='somenum1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='somenum2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='somenum3',
        ),
        migrations.AddField(
            model_name='products',
            name='ezdim',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='kol',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='netto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stoim',
            field=models.IntegerField(null=True),
        ),
    ]
