# Generated by Django 4.1.2 on 2022-11-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lct4', '0005_alter_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ezdim',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='kol',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='netto',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='stoim',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
