# Generated by Django 4.1.2 on 2022-11-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lct4', '0006_alter_products_ezdim_alter_products_kol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='direction',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='products',
            name='ezdim',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='kol',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='netto',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='products',
            name='stoim',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
