# Generated by Django 4.1.2 on 2022-11-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lct4', '0007_alter_products_direction_alter_products_ezdim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Коды',
                'verbose_name_plural': 'Коды',
            },
        ),
    ]
