# Generated by Django 4.1.2 on 2022-11-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lct4', '0008_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Регионы',
                'verbose_name_plural': 'Регионы',
            },
        ),
    ]
